### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by techman-001** [ekoeppen/janus#10]
Hi,

I'm trying to build your Coreforth with Janus (very exciting) and have failed on a recent Linux and FreeBSD box and I get the same errors listed below.
I have read everything in your Janus release.

 I'm a electronics tech and not a real programmer so it is more than likely something I'm doing wrong. I've tested your CoreForth-master from 2017 on a STM32F103 and found it very interesting, hence my interest in your most recent work.

I started and have maintained this website for a few years now " The Unofficial Mecrisp-Stellaris Doc" which is really my own notes as I worked my way into Forth back in 2014. [Mecrisp-Stellaris](https://mecrisp-stellaris-folkdoc.sourceforge.io) The F051 is also my MCU of choice, in a 32 pin QFN package.

`root@mx19:/usr/local/src/janus# make
gforth janus.ft CoreForth-0/cortex/boards/thumbulator-m3.ft stc

deferred word timmediate is uninitialized
deferred word timmediate is uninitialized
deferred word timmediate is uninitialized
in file included from *OS command line*:-1
janus.ft:166: No such file or directory
source-file count >>>included<<<
Backtrace:
$7FDE71D0DEE0 throw 
make: *** [Makefile:5: janus.hex] Error 1`

Thanks in advance for any light you could throw on this matter,

Best Regards
Terry Porter

**Comment by ekoeppen** [comment]
Right, I think I forgot to update the Makefile in my recent changes! It is now updated, and I also added some info to the README how to compile in general. Hope it works for you!
